test workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,1 +1,63 @@
+name: demo_fastapi workflow
+
+on: [push]
+
+jobs:
+  tests:
+    runs-on: ubuntu-latest
+    
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+        with:
+          driver-opts: |
+            image=moby/buildkit:latest
+
+      - name: Build Docker image
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          load: true
+          tags: user-gateway:test
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+
+      - name: Run container test
+        run: |
+          # Запускаем контейнер
+          docker run -d -p 8000:8000 --name api-test user-gateway:test
+          
+          echo "Waiting for app to start..."
+          for i in {1..60}; do
+            if curl -s http://localhost:8000/health >/dev/null; then
+              echo "App is ready!"
+              break
+            fi
+            sleep 2
+          done
+          
+          response=$(curl -s -w "%{http_code}" -o response.json http://localhost:8000/)
+          status_code=$(tail -n1 <<< "$response")
+
+          echo "Response: $response"
+
+          if [[ "$status_code" == "200" ]] && grep -q '"message":"HEllo from User Application"' response.json; then
+            echo "Main endpoint test passed"
+          else
+            echo "Main endpoint test failed!"
+            exit 1
+          fi
+          
+          docker stop api-test
+          docker rm api-test
+      
+      - name: Security scan
+        uses: aquasecurity/trivy-action@master
+        with:
+          image-ref: user-gateway:test
+          format: 'sarif'
+          output: 'trivy-results.sarif'
 
